### ISSUE TITLE
PubTables1M-PDF-Annotations-JSON annotations do not match the images in PubTables1M-Structure-PASCAL-VOC

### ISSUE THREAD

**Issue by iazdan** [microsoft/table-transformer#43]
The bboxes of the json files in the folder "PubTables1M-PDF-Annotations-JSON"  do not match the images in the folder "PubTables1M-Structure-PASCAL-VOC". Do we need to apply any transformation on the images? 
For example I removed 30 pixels from each side of the image but the bboxes still do not fit the texts inside the tables.
![tst-222](https://user-images.githubusercontent.com/17073596/167873170-aebc8197-9893-41ab-ad76-3ddda95af64b.jpg)

**Comment by bsmock** [comment]
The annotations in the JSON files are in PDF coordinates, so yes some transformation steps are required if you want to visualize those directly onto the cropped table images.

If you just want to visualize the data, it will be easier to do the transform to visualize the table annotations on top of the page images instead of the cropped table images.

In this case, for a table, the size of the page it's on in PDF coordinates is contained in the field "pdf_full_page_bbox". The page images are all scaled to have a maximum length (width or height) of 1000. To transform from PDF page coordinates to page image coordinates, you need to compute and apply the scaling factor both for x coordinates and for y coordinates:

x_scale = image_width / PDF_width
y_scale = image_height / PDF_height

Then any bbox in PDF coordinates can be transformed to its page image equivalent using:
image_bbox = [x_scale*pdf_bbox[0], y_scale*pdf_bbox[1], x_scale*pdf_bbox[2], y_scale*pdf_bbox[3]]

I should add that I haven't actually verified on real data that the above is correct. Let us know if you're still having issues visualizing the data.
